### ISSUE TITLE
Gzip encoding

### ISSUE THREAD

**Issue by LynxyssCZ** [wilson428/downcache#1]
Hi, I tried to use your library for caching request to api that uses gzip for responses, but under no circumstances was I able to set gzip to true on the underlying request library.

I was able to patch it in manually but it would be nice to be able to configure the Request library directly in opts object and by .set method.

**Comment by wilson428** [comment]
This came up the other day with allowing for POST requests as well. Happy to look at a PR, or I can add sometime soon. What's the ideal syntax? I could add a `request` option to the options object that passes through to the module, I guess:

     downcache(url, { request: { gzip: true } }, function(err, resp, body) {  .... });

**Comment by LynxyssCZ** [comment]
Pull Request #2 now open.
I didn't use any other nested object because it didn't sit right with me.

**Comment by wilson428** [comment]
Merged! Thanks much, @LynxyssCZ. Per my comment on the PR, would be grateful for an example of a call that requires gzip to be true for the `npm test` function.

**Comment by LynxyssCZ** [comment]
You should be able to reuse most of the request tests, gzip one is here https://github.com/request/request/blob/a2c9ec7e28567bd58837b106abe1b9a03d881e1d/tests/test-gzip.js
